markdown: kramdown
redcarpet:
extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: 
permalink: none
exclude: 
url: https://davelab6.github.io
title: John Taylor Gatto Archive
